### ISSUE TITLE
Code coverage átnézése, tesztek javítása

### ISSUE THREAD

**Issue by 0x19846669** [BME-MIT-IET/Exiles-iet-2018#14]
Néhány teszt kiegészítése, hogy jobb kódlefedettséget érjünk el, ezáltal csökkentve a hibás kód valószínűségét.

**Comment by chris914** [comment]
A HardGraphMatching.cs osztály 328. sorában levő feltétel nincs lefedve a kód által, ugyanis a tesztek random seeddel hívják ezt a függvényt. Javaslom hogy vegyünk fel egy új tesztet, amiben a seedet úgy állítjuk be, hogy az ág tesztelésre kerüljön.

**Comment by 0x19846669** [comment]
A Testing/unittest/Core/BasicTest1.cs 545. sorától kezdődő catch ág fölösleges, a finally ág pontosan ugyanazt állítja be, a kivétel tovább dobására sincs szükség ha nem kapjuk el.
Javítva: 87834f627ef683d18801a8936904038bbfe2fb77

**Comment by chris914** [comment]
3c00c55b248bee2d22dffaf29ed6410ca1a1eea6 javítva az általam feljebb írtakat.

**Comment by 0x19846669** [comment]
A komplexitás redukció utáni állapottal való összefésülés érdekében az eddig elkészült javításokat a #27 -es pull request tartalmazza.

**Comment by 0x19846669** [comment]
A redukció utáni elkészült egy újabb code coverage javítás, ezt a #28-as pull request őrzi.
