### ISSUE TITLE
Egységtesztek

### ISSUE THREAD

**Issue by 0x19846669** [BME-MIT-IET/Exiles-iet-2018#15]
Új egységtesztek írása és/vagy meglévők javítása, valamint a sikertelen tesztek átnézése, kód javítása.

**Comment by 0x19846669** [comment]
Az AppVeyor elindítása után kikommentezett, hibás teszteket ellenőrizni kell, esetlegesen kijavítani a dotNetDRF vagy a teszt hibáit.

**Comment by chris914** [comment]
A teszteket ellenőríztük, bővítettük. #20

**Comment by 0x19846669** [comment]
A Core részhez nem találtunk módot további érdemleges tesztek írására, ezért lezárom az issuet.
