### ISSUE TITLE
CI a projecthez

### ISSUE THREAD

**Issue by 0x19846669** [BME-MIT-IET/Exiles-iet-2018#3]
Az eredeti project AppVeyor CI-hez lett hozzáadva, ezért ezt használjuk mi is.
(Egy Travis config fájl meggondolatlanul hozzá lett adva a repo-hoz, ezt kijavítom.)

**Comment by chris914** [comment]
Igazolom, hogy az AppVeyor integrálva lett a rendszerbe, a kikommentezett tesztek után hiba nélkül lefutott.
